$(document).ready(function()
{
    $(".cl").hide();
    $(".last1").click(function()
    {
        $(".cl1").toggle(1500);
    });
    $(".last2").click(function()
    {
        $(".cl2").toggle(1500);
    });
    $(".last3").click(function()
    {
        $(".cl3").toggle(1500);
    });
});